### ISSUE TITLE
The code assumes that document.body is present. This is not always the case

### ISSUE THREAD

**Issue by dkamyshov** [smff/dom-pubsub#1]
Calls to publishDOM and subscribeDOM will fail in case document.body is not present.

See: https://developer.mozilla.org/en-US/docs/Web/API/Document/body

> The Document.body property represents the `<body>` or `<frameset>` node of the current document, or **null** if no such element exists.

**Comment by smff** [comment]
yep, you can open PR to prevent this behavior)

**Comment by smff** [comment]
Thnx, can you please open PR? I'll fix this

**Comment by smff** [comment]
done
